### ISSUE TITLE
unable to compile with 13.0.1

### ISSUE THREAD

**Issue by anjith-sm** [Opteo/google-ads-api#470]
Our Typescript version is 4.9.4. When compiling getting the following issue:

```
node_modules/google-ads-api/build/src/hooks.d.ts:10:16 - error TS2322: Type 'string | number | symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
  Type 'symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.

10     method: `${keyof typeof services}.${string}`;
                  ~~~~~~~~~~~~~~~~~~~~~

node_modules/google-ads-api/build/src/hooks.d.ts:21:16 - error TS2322: Type 'string | number | symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.

21     method: `${keyof typeof services}.${string}`;
                  ~~~~~~~~~~~~~~~~~~~~~

node_modules/google-ads-api/build/src/protos/index.d.ts:1:35 - error TS7016: Could not find a declaration file for module 'google-ads-node'. '/Users/sss/sc/app/libs/google-ads-api-client/node_modules/google-ads-node/build/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/google-ads-node` if it exists or add a new declaration (.d.ts) file containing `declare module 'google-ads-node';`

1 import allProtos, { protos } from "google-ads-node";
                                    ~~~~~~~~~~~~~~~~~

node_modules/google-ads-api/build/src/protos/index.d.ts:10:40 - error TS7016: Could not find a declaration file for module 'google-ads-node'. '/Users/sss/sc/app/libs/google-ads-api-client/node_modules/google-ads-node/build/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/google-ads-node` if it exists or add a new declaration (.d.ts) file containing `declare module 'google-ads-node';`

10 export { GoogleAdsServiceClient } from "google-ads-node";
                                          ~~~~~~~~~~~~~~~~~
```

We tried adding a module declaration file for `google-ads-node`  package explicitly but that doesn't seem to help either. Are we missing anything else ?
