### ISSUE TITLE
customer.accountBudgets.list is not a function

### ISSUE THREAD

**Issue by AshwanthMadhav** [Opteo/google-ads-api#262]
const { GoogleAdsApi } = require('google-ads-api');
                    const client = new GoogleAdsApi({
                        client_id: clientId,
                        client_secret: clientSecret,
                        developer_token: developerToken,
                    })

                    let customer = client.Customer({
                        customer_id: accId,
                        login_customer_id: clientCustomerId, // Optionally provide a login-customer-id
                        refresh_token: refreshToken,
                    })

                    let cutomerDetailsPromise = customer.report({
                        entity: 'customer',
                        attributes: [
                            "customer.descriptive_name",
                            "customer.manager",
                            "customer.resource_name",
                            "customer.id",
                        ],
                    })

                    let budgetPromise = customer.accountBudgets.list()

This was working a few mnths ago. But currently getting error `customer.accountBudgets.list is not a function`?

**Comment by kritzware** [comment]
In a recent version the `list` methods were removed, instead you should select the specific fields you want with `customer.report`. For a full list of the breaking changes when we upgraded to V6, check out [these notes](https://github.com/Opteo/google-ads-api/pull/201#issuecomment-788933339).

**Comment by AshwanthMadhav** [comment]
Okay. Let me try it

**Comment by AshwanthMadhav** [comment]
Thanks. Its working.
