### ISSUE TITLE
customer.campaigns.list is not a function

### ISSUE THREAD

**Issue by esp-sonnt** [Opteo/google-ads-api#293]
Hi,
I'm using:
- node.js `v14.17.0`
- google-ads-api version `^5.2.0`

Following the instruction of the library but my code exit with `customer.campaigns.list is not a function`. Below is my code. Can anyone help me with this issue? Thanks a lot.
```
const client = new GoogleAdsApi({
    client_id: process.env.GOOGLE_APP_ID,
    client_secret: process.env.GOOGLE_APP_SECRET,
    developer_token: process.env.GOOGLE_DEVELOPER_TOKEN,
});
const customer = client.Customer({
    customer_account_id: 'xxx-xxx-xxxx', // my Google Ads ID Linked with MCC 
    login_customer_id: 'yyyy-yyy-yyyy', // my MCC id
    refresh_token: refreshToken,
});
const campaigns = await customer.campaigns.list();
console.log(campaigns);
return campaigns;
```

**Comment by matcwhite** [comment]
I'm having exactly the same problem. The following do not work:
`customer.campaigns.list()`
`customer.adGroups.list()`
Example:

```
const { GoogleAdsApi } = require('google-ads-api');

const client = new GoogleAdsApi({
	client_id: "<CLIENT_ID>",
	client_secret: "<CLIENT_SECRET>",
	developer_token: "<DEVELOPER_TOKEN>"
});

const refreshToken = '<REFRESH_TOKEN>';


async function main(){
	

	const customer = client.Customer({
		customer_id: "1234567890",
		refresh_token: refreshToken,
	});
		

	let result = await customer.adGroups.list();
	

}
```



This throws an error 
`UnhandledPromiseRejectionWarning: TypeError: customer.adGroups.list is not a function`
What's going on??

**Comment by WillCooter** [comment]
In a recent version of the API the `list` methods were removed, instead you should select the specific fields you want with `customer.report`. For a full list of the breaking changes when we upgraded to V6, check out [these notes](https://github.com/Opteo/google-ads-api/pull/201#issuecomment-788933339).

**Comment by matcwhite** [comment]
Ahh, that does explain it. Thank you very much indeed.
Mat
