### ISSUE TITLE
customer.campaigns.list() returns `TypeError: customer.campaigns.list is not a function`

### ISSUE THREAD

**Issue by alihardan** [Opteo/google-ads-api#337]
Hello and thanks for this project.

``` javascript
import { GoogleAdsApi } from 'google-ads-api'

const client = new GoogleAdsApi({
    client_id: 'XXX',
    client_secret: 'XXX',
    developer_token: 'XXX',
})

const customer = client.Customer({
    customer_account_id: 'XXX',
    refresh_token: 'XXX',
})

// If done correctly, you should now be able to list the campaigns in the account 123-123-123
customer.campaigns.list()
```

output:

``` bash
$ node main.js
file:///x/y/z/main.js:17
customer.campaigns.list()
                   ^

TypeError: customer.campaigns.list is not a function
    at file:///x/y/z/main.js:17:20
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```

**Comment by WillCooter** [comment]
Hi @alihardan. In a recent version of the API the `list` methods were removed, instead you should select the specific fields you want with `customer.report`. For a full list of the breaking changes when we upgraded to V6, check out [these notes](https://github.com/Opteo/google-ads-api/pull/201#issuecomment-788933339).
